version: '3.9'
services:
  react-project:
    build:
      context: ./ # Dockerfileのある場所指定
      dockerfile: Dockerfile
    container_name: react-project
    volumes:
      - ./:/react-project
    ports:
      - "3000:3000"